### ISSUE TITLE
Use better default

### ISSUE THREAD

**Issue by djberg96** [zencoder/net-ntp#10]
At the moment the default ntp server is pool.ntp.org.

However, this will not always be valid, and will cause timeout errors if a different ntp server is specified in the /etc/ntp.conf file. At least, that's been my experience on my RHEL 7 laptop.

I was thinking something along these lines might be good:

`IO.read("/etc/ntp.conf")[/^server\s([\p{Alnum}\.]*)/, 1] || 'pool.ntp.org'`

"Why not just specify that as an argument?", you might ask. The answer is that first, it means I have to go digging into my /etc/ntp.conf file to find the server(s). Second, if this is being used on multiple remote systems, each potentially having their own unique /etc/ntp.conf entries, it would simply not be practical.

You could, of course, get fancier with multiple server entries and retry failures and whatnot, but I'd be happy with just this for starters, at least on unixy systems.

**Comment by nate** [comment]
I appreciate the issue, however I don't think this library should be in the business of parsing NTP configuration files. Additionally, at its core the purpose of this library is to query NTP independently of any system configuration. I'm not sure how your system is intercepting UDP requests to NTP servers but that's something to look into.
